# Use the official Node.js image as a parent image
FROM mcr.microsoft.com/devcontainers/javascript-node

# Set the working directory in the container
WORKDIR /workspace
USER node


# Expose port 3000 for the application
EXPOSE 3000

# Set the default command to start the application
CMD ["pnpm", "dev"]
